//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatisProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class CokSatanlar
    {
        public string Adi { get; set; }
        public Nullable<int> ToplamAlisAdedi { get; set; }
        public Nullable<decimal> ToplamAlisFiyati { get; set; }
        public Nullable<decimal> OrtalamaAlisFiyati { get; set; }
        public Nullable<int> ToplamSatisAdedi { get; set; }
        public Nullable<decimal> ToplamSatisFiyati { get; set; }
        public Nullable<decimal> OrtalamaSatisFiyati { get; set; }
    }
}
