//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatisProje
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SatisProjeEntities : DbContext
    {
        public SatisProjeEntities()
            : base("name=SatisProjeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Birimalttipi> Birimalttipi { get; set; }
        public virtual DbSet<Birimtipi> Birimtipi { get; set; }
        public virtual DbSet<Iliskiler> Iliskiler { get; set; }
        public virtual DbSet<Kategori> Kategori { get; set; }
        public virtual DbSet<Odemeler> Odemeler { get; set; }
        public virtual DbSet<Siparisler> Siparisler { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Urunler> Urunler { get; set; }
        public virtual DbSet<CokSatanlar> CokSatanlar { get; set; }
    
        public virtual int ILISKI_INSERT(string iliski_tipi, string kodu, string yetkili_kisi, string email, string telefon, string adres, string kayit_durumu)
        {
            var iliski_tipiParameter = iliski_tipi != null ?
                new ObjectParameter("Iliski_tipi", iliski_tipi) :
                new ObjectParameter("Iliski_tipi", typeof(string));
    
            var koduParameter = kodu != null ?
                new ObjectParameter("Kodu", kodu) :
                new ObjectParameter("Kodu", typeof(string));
    
            var yetkili_kisiParameter = yetkili_kisi != null ?
                new ObjectParameter("Yetkili_kisi", yetkili_kisi) :
                new ObjectParameter("Yetkili_kisi", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var telefonParameter = telefon != null ?
                new ObjectParameter("Telefon", telefon) :
                new ObjectParameter("Telefon", typeof(string));
    
            var adresParameter = adres != null ?
                new ObjectParameter("Adres", adres) :
                new ObjectParameter("Adres", typeof(string));
    
            var kayit_durumuParameter = kayit_durumu != null ?
                new ObjectParameter("Kayit_durumu", kayit_durumu) :
                new ObjectParameter("Kayit_durumu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ILISKI_INSERT", iliski_tipiParameter, koduParameter, yetkili_kisiParameter, emailParameter, telefonParameter, adresParameter, kayit_durumuParameter);
        }
    
        public virtual int KATEGORI_INSERT(string adi, string kayit_durumu)
        {
            var adiParameter = adi != null ?
                new ObjectParameter("Adi", adi) :
                new ObjectParameter("Adi", typeof(string));
    
            var kayit_durumuParameter = kayit_durumu != null ?
                new ObjectParameter("Kayit_durumu", kayit_durumu) :
                new ObjectParameter("Kayit_durumu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("KATEGORI_INSERT", adiParameter, kayit_durumuParameter);
        }
    
        public virtual int MUHASEBE_INSERT(string islem_tipi, Nullable<int> iliski_id, Nullable<decimal> islem_bakiye, Nullable<System.DateTime> tarih, string aciklama)
        {
            var islem_tipiParameter = islem_tipi != null ?
                new ObjectParameter("Islem_tipi", islem_tipi) :
                new ObjectParameter("Islem_tipi", typeof(string));
    
            var iliski_idParameter = iliski_id.HasValue ?
                new ObjectParameter("Iliski_id", iliski_id) :
                new ObjectParameter("Iliski_id", typeof(int));
    
            var islem_bakiyeParameter = islem_bakiye.HasValue ?
                new ObjectParameter("Islem_bakiye", islem_bakiye) :
                new ObjectParameter("Islem_bakiye", typeof(decimal));
    
            var tarihParameter = tarih.HasValue ?
                new ObjectParameter("Tarih", tarih) :
                new ObjectParameter("Tarih", typeof(System.DateTime));
    
            var aciklamaParameter = aciklama != null ?
                new ObjectParameter("Aciklama", aciklama) :
                new ObjectParameter("Aciklama", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MUHASEBE_INSERT", islem_tipiParameter, iliski_idParameter, islem_bakiyeParameter, tarihParameter, aciklamaParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int URUN_INSERT(string kodu, string adi, Nullable<int> uyari_limiti, Nullable<int> kategori_id, Nullable<int> birim_tipi, string kayit_durumu)
        {
            var koduParameter = kodu != null ?
                new ObjectParameter("Kodu", kodu) :
                new ObjectParameter("Kodu", typeof(string));
    
            var adiParameter = adi != null ?
                new ObjectParameter("Adi", adi) :
                new ObjectParameter("Adi", typeof(string));
    
            var uyari_limitiParameter = uyari_limiti.HasValue ?
                new ObjectParameter("Uyari_limiti", uyari_limiti) :
                new ObjectParameter("Uyari_limiti", typeof(int));
    
            var kategori_idParameter = kategori_id.HasValue ?
                new ObjectParameter("Kategori_id", kategori_id) :
                new ObjectParameter("Kategori_id", typeof(int));
    
            var birim_tipiParameter = birim_tipi.HasValue ?
                new ObjectParameter("Birim_tipi", birim_tipi) :
                new ObjectParameter("Birim_tipi", typeof(int));
    
            var kayit_durumuParameter = kayit_durumu != null ?
                new ObjectParameter("Kayit_durumu", kayit_durumu) :
                new ObjectParameter("Kayit_durumu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("URUN_INSERT", koduParameter, adiParameter, uyari_limitiParameter, kategori_idParameter, birim_tipiParameter, kayit_durumuParameter);
        }
    
        public virtual int BIRIMALTTIPI_INSERT(string adi, Nullable<int> birim_tipi_id, string kayit_durumu)
        {
            var adiParameter = adi != null ?
                new ObjectParameter("Adi", adi) :
                new ObjectParameter("Adi", typeof(string));
    
            var birim_tipi_idParameter = birim_tipi_id.HasValue ?
                new ObjectParameter("Birim_tipi_id", birim_tipi_id) :
                new ObjectParameter("Birim_tipi_id", typeof(int));
    
            var kayit_durumuParameter = kayit_durumu != null ?
                new ObjectParameter("Kayit_durumu", kayit_durumu) :
                new ObjectParameter("Kayit_durumu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BIRIMALTTIPI_INSERT", adiParameter, birim_tipi_idParameter, kayit_durumuParameter);
        }
    
        public virtual int BIRIMTIPI_INSERT(string adi, string kayit_durumu)
        {
            var adiParameter = adi != null ?
                new ObjectParameter("Adi", adi) :
                new ObjectParameter("Adi", typeof(string));
    
            var kayit_durumuParameter = kayit_durumu != null ?
                new ObjectParameter("Kayit_durumu", kayit_durumu) :
                new ObjectParameter("Kayit_durumu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BIRIMTIPI_INSERT", adiParameter, kayit_durumuParameter);
        }
    
        public virtual int URUNISLEMLERI_INSERT(string islem_tipi, Nullable<int> urun_id, Nullable<int> iliski_id, Nullable<int> birim_alttipi_id, Nullable<int> miktar, Nullable<decimal> birim_fiyat, Nullable<decimal> toplam_fiyat, Nullable<decimal> pesin_odenen, Nullable<decimal> islem_bakiye, Nullable<System.DateTime> tarih, string aciklama)
        {
            var islem_tipiParameter = islem_tipi != null ?
                new ObjectParameter("Islem_tipi", islem_tipi) :
                new ObjectParameter("Islem_tipi", typeof(string));
    
            var urun_idParameter = urun_id.HasValue ?
                new ObjectParameter("Urun_id", urun_id) :
                new ObjectParameter("Urun_id", typeof(int));
    
            var iliski_idParameter = iliski_id.HasValue ?
                new ObjectParameter("Iliski_id", iliski_id) :
                new ObjectParameter("Iliski_id", typeof(int));
    
            var birim_alttipi_idParameter = birim_alttipi_id.HasValue ?
                new ObjectParameter("Birim_alttipi_id", birim_alttipi_id) :
                new ObjectParameter("Birim_alttipi_id", typeof(int));
    
            var miktarParameter = miktar.HasValue ?
                new ObjectParameter("Miktar", miktar) :
                new ObjectParameter("Miktar", typeof(int));
    
            var birim_fiyatParameter = birim_fiyat.HasValue ?
                new ObjectParameter("Birim_fiyat", birim_fiyat) :
                new ObjectParameter("Birim_fiyat", typeof(decimal));
    
            var toplam_fiyatParameter = toplam_fiyat.HasValue ?
                new ObjectParameter("Toplam_fiyat", toplam_fiyat) :
                new ObjectParameter("Toplam_fiyat", typeof(decimal));
    
            var pesin_odenenParameter = pesin_odenen.HasValue ?
                new ObjectParameter("Pesin_odenen", pesin_odenen) :
                new ObjectParameter("Pesin_odenen", typeof(decimal));
    
            var islem_bakiyeParameter = islem_bakiye.HasValue ?
                new ObjectParameter("Islem_bakiye", islem_bakiye) :
                new ObjectParameter("Islem_bakiye", typeof(decimal));
    
            var tarihParameter = tarih.HasValue ?
                new ObjectParameter("Tarih", tarih) :
                new ObjectParameter("Tarih", typeof(System.DateTime));
    
            var aciklamaParameter = aciklama != null ?
                new ObjectParameter("Aciklama", aciklama) :
                new ObjectParameter("Aciklama", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("URUNISLEMLERI_INSERT", islem_tipiParameter, urun_idParameter, iliski_idParameter, birim_alttipi_idParameter, miktarParameter, birim_fiyatParameter, toplam_fiyatParameter, pesin_odenenParameter, islem_bakiyeParameter, tarihParameter, aciklamaParameter);
        }
    
        public virtual int ILISKI_GUNCELLE(string iliski_tipi, string kodu, string yetkili_kisi, string adres, string telefon, string email, string kayit_durumu, Nullable<int> guncellenecek_id)
        {
            var iliski_tipiParameter = iliski_tipi != null ?
                new ObjectParameter("Iliski_tipi", iliski_tipi) :
                new ObjectParameter("Iliski_tipi", typeof(string));
    
            var koduParameter = kodu != null ?
                new ObjectParameter("Kodu", kodu) :
                new ObjectParameter("Kodu", typeof(string));
    
            var yetkili_kisiParameter = yetkili_kisi != null ?
                new ObjectParameter("Yetkili_kisi", yetkili_kisi) :
                new ObjectParameter("Yetkili_kisi", typeof(string));
    
            var adresParameter = adres != null ?
                new ObjectParameter("Adres", adres) :
                new ObjectParameter("Adres", typeof(string));
    
            var telefonParameter = telefon != null ?
                new ObjectParameter("Telefon", telefon) :
                new ObjectParameter("Telefon", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var kayit_durumuParameter = kayit_durumu != null ?
                new ObjectParameter("Kayit_durumu", kayit_durumu) :
                new ObjectParameter("Kayit_durumu", typeof(string));
    
            var guncellenecek_idParameter = guncellenecek_id.HasValue ?
                new ObjectParameter("guncellenecek_id", guncellenecek_id) :
                new ObjectParameter("guncellenecek_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ILISKI_GUNCELLE", iliski_tipiParameter, koduParameter, yetkili_kisiParameter, adresParameter, telefonParameter, emailParameter, kayit_durumuParameter, guncellenecek_idParameter);
        }
    
        public virtual int URUN_GUNCELLE(string kodu, string adi, Nullable<int> kategori_id, Nullable<int> uyari_limiti, Nullable<int> birim_tipi, string kayit_durumu, Nullable<int> guncellenecek_id)
        {
            var koduParameter = kodu != null ?
                new ObjectParameter("Kodu", kodu) :
                new ObjectParameter("Kodu", typeof(string));
    
            var adiParameter = adi != null ?
                new ObjectParameter("Adi", adi) :
                new ObjectParameter("Adi", typeof(string));
    
            var kategori_idParameter = kategori_id.HasValue ?
                new ObjectParameter("Kategori_id", kategori_id) :
                new ObjectParameter("Kategori_id", typeof(int));
    
            var uyari_limitiParameter = uyari_limiti.HasValue ?
                new ObjectParameter("Uyari_limiti", uyari_limiti) :
                new ObjectParameter("Uyari_limiti", typeof(int));
    
            var birim_tipiParameter = birim_tipi.HasValue ?
                new ObjectParameter("Birim_tipi", birim_tipi) :
                new ObjectParameter("Birim_tipi", typeof(int));
    
            var kayit_durumuParameter = kayit_durumu != null ?
                new ObjectParameter("Kayit_durumu", kayit_durumu) :
                new ObjectParameter("Kayit_durumu", typeof(string));
    
            var guncellenecek_idParameter = guncellenecek_id.HasValue ?
                new ObjectParameter("guncellenecek_id", guncellenecek_id) :
                new ObjectParameter("guncellenecek_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("URUN_GUNCELLE", koduParameter, adiParameter, kategori_idParameter, uyari_limitiParameter, birim_tipiParameter, kayit_durumuParameter, guncellenecek_idParameter);
        }
    
        public virtual int KATEGORI_GUNCELLE(string adi, string kayit_durumu, Nullable<int> guncellenecek_id)
        {
            var adiParameter = adi != null ?
                new ObjectParameter("Adi", adi) :
                new ObjectParameter("Adi", typeof(string));
    
            var kayit_durumuParameter = kayit_durumu != null ?
                new ObjectParameter("Kayit_durumu", kayit_durumu) :
                new ObjectParameter("Kayit_durumu", typeof(string));
    
            var guncellenecek_idParameter = guncellenecek_id.HasValue ?
                new ObjectParameter("guncellenecek_id", guncellenecek_id) :
                new ObjectParameter("guncellenecek_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("KATEGORI_GUNCELLE", adiParameter, kayit_durumuParameter, guncellenecek_idParameter);
        }
    
        public virtual int BIRIMALTTIPI_GUNCELLE(string adi, Nullable<int> birim_tipi_id, string kayit_durumu, Nullable<int> guncellenecek_id)
        {
            var adiParameter = adi != null ?
                new ObjectParameter("Adi", adi) :
                new ObjectParameter("Adi", typeof(string));
    
            var birim_tipi_idParameter = birim_tipi_id.HasValue ?
                new ObjectParameter("Birim_tipi_id", birim_tipi_id) :
                new ObjectParameter("Birim_tipi_id", typeof(int));
    
            var kayit_durumuParameter = kayit_durumu != null ?
                new ObjectParameter("Kayit_durumu", kayit_durumu) :
                new ObjectParameter("Kayit_durumu", typeof(string));
    
            var guncellenecek_idParameter = guncellenecek_id.HasValue ?
                new ObjectParameter("guncellenecek_id", guncellenecek_id) :
                new ObjectParameter("guncellenecek_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BIRIMALTTIPI_GUNCELLE", adiParameter, birim_tipi_idParameter, kayit_durumuParameter, guncellenecek_idParameter);
        }
    
        public virtual int BIRIMTIPI_GUNCELLE(string adi, string kayit_durumu, Nullable<int> guncellenecek_id)
        {
            var adiParameter = adi != null ?
                new ObjectParameter("Adi", adi) :
                new ObjectParameter("Adi", typeof(string));
    
            var kayit_durumuParameter = kayit_durumu != null ?
                new ObjectParameter("Kayit_durumu", kayit_durumu) :
                new ObjectParameter("Kayit_durumu", typeof(string));
    
            var guncellenecek_idParameter = guncellenecek_id.HasValue ?
                new ObjectParameter("guncellenecek_id", guncellenecek_id) :
                new ObjectParameter("guncellenecek_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BIRIMTIPI_GUNCELLE", adiParameter, kayit_durumuParameter, guncellenecek_idParameter);
        }
    }
}
