//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatisProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparisler
    {
        public int Id { get; set; }
        public string Islem_tipi { get; set; }
        public int Urun_id { get; set; }
        public int Iliski_id { get; set; }
        public int Birim_alttipi_id { get; set; }
        public int Miktar { get; set; }
        public decimal Birim_fiyat { get; set; }
        public decimal Toplam_fiyat { get; set; }
        public decimal Pesin_odenen { get; set; }
        public decimal Islem_bakiye { get; set; }
        public System.DateTime Tarih { get; set; }
        public string Aciklama { get; set; }
    
        public virtual Birimalttipi Birimalttipi { get; set; }
        public virtual Iliskiler Iliskiler { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
